import { TripItem, AvailabilityStatus } from '@/lib/store';

export interface Product extends TripItem {
  description: string;
  descriptionEs?: string;
  descriptionEn?: string;
  fullDescription?: string;
  itinerary?: Array<{
    day: string;
    title: string;
  }>;
  includes?: string[];
  notIncludes?: string[];
  closingTitle?: string;
  closingText?: string;
  ctaLabel?: string;
  whatToBring?: string[];
  meetingPoint?: string;
  importantInfo?: string;
  schedule?: string;
  minPeople?: number;
  maxPeople?: number;
  languages?: string[];
  tags?: string[];
  gallery?: string[];
  featured?: boolean;
  badge?: 'popular' | 'new' | 'recommended' | 'sale';
  relatedProducts?: string[];
  priceChild?: number;
  priceSale?: number;
}

export const sampleProducts: Product[] = [
  {
    id: 'valle-de-la-luna',
    slug: 'valle-de-la-luna',
    name: 'Valle de la Luna & Miradores',
    nameEs: 'Valle de la Luna & Miradores',
    nameEn: 'Valley of the Moon & Viewpoints',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: '/images/valle-de-la-luna.jpg',
    gallery: [
      '/images/valle-de-la-luna.jpg',
      '/images/hero-principal.jpg',
    ],
    description: 'Um dos cenários mais surreais do Atacama. Formações de sal, crateras e cores que mudam com a luz do entardecer.',
    descriptionEs: 'Uno de los paisajes más surrealistas del Atacama. Formaciones de sal, cráteres y colores que cambian con la luz del atardecer.',
    descriptionEn: 'One of the most surreal landscapes in the Atacama. Salt formations, craters and colors that change with the evening light.',
    duration: '5 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    price: undefined,
    featured: true,
    badge: 'popular',
    tags: ['natureza', 'cultura', 'pôr-do-sol'],
    includes: ['Transporte', 'Guia local', 'Entrada ao parque'],
    notIncludes: ['Alimentação', 'Gorjetas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'lagunas-altiplanicas',
    slug: 'lagunas-altiplanicas',
    name: 'Lagunas Altiplânicas',
    nameEs: 'Lagunas Altiplánicas',
    nameEn: 'Altiplanic Lagoons',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: 'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=800&q=80',
    description: 'Lagoas de altitude com flamingos e paisagens de outro mundo. Um espetáculo da natureza altiplânica.',
    descriptionEs: 'Lagunas de altura con flamencos y paisajes de otro mundo. Un espectáculo de la naturaleza altiplánica.',
    descriptionEn: 'High-altitude lagoons with flamingos and otherworldly landscapes. A natural spectacle of the altiplano.',
    duration: '8 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'recommended',
    tags: ['natureza', 'aventura', 'fauna'],
    includes: ['Transporte 4x4', 'Guia', 'Box lunch'],
    notIncludes: ['Gorjetas', 'Bebidas extras'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'geysers-del-tatio',
    slug: 'geysers-del-tatio',
    name: 'Geysers del Tatio',
    nameEs: 'Géiseres del Tatio',
    nameEn: 'El Tatio Geysers',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: '/images/geysers-del-tatio.jpg',
    description: 'Campo de geysers a 4.320m de altitude. Um espetáculo geotérmico ao amanhecer no coração do Atacama.',
    descriptionEs: 'Campo de géiseres a 4.320m de altitud. Un espectáculo geotérmico al amanecer en el corazón del Atacama.',
    descriptionEn: 'Geyser field at 4,320m altitude. A geothermal spectacle at dawn in the heart of the Atacama.',
    duration: '6 horas',
    availability: 'few-spots',
    adults: 2,
    children: 0,
    featured: true,
    tags: ['natureza', 'aventura', 'madrugada'],
    includes: ['Transporte', 'Guia', 'Café da manhã'],
    notIncludes: ['Seguro viagem', 'Gorjetas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'machu-picchu-day',
    slug: 'machu-picchu-day',
    name: 'Machu Picchu — Dia Completo',
    nameEs: 'Machu Picchu — Día Completo',
    nameEn: 'Machu Picchu — Full Day',
    destination: 'Cusco',
    country: 'Peru',
    category: 'experiences',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'A cidade perdida dos Incas em toda sua magnitude. Tour completo com guia especializado e trem turístico.',
    descriptionEs: 'La ciudad perdida de los Incas en toda su magnitud. Tour completo con guía especializado y tren turístico.',
    descriptionEn: 'The lost city of the Incas in all its magnitude. Complete tour with specialized guide and tourist train.',
    duration: '12 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['cultura', 'história', 'patrimônio'],
    includes: ['Trem de ida e volta', 'Ingresso Machu Picchu', 'Guia'],
    notIncludes: ['Alimentação', 'Ônibus subida/descida opcional'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'salar-de-uyuni',
    slug: 'salar-de-uyuni',
    name: 'Salar de Uyuni — Tour Clássico',
    nameEs: 'Salar de Uyuni — Tour Clásico',
    nameEn: 'Salar de Uyuni — Classic Tour',
    destination: 'Uyuni',
    country: 'Bolívia',
    category: 'tours',
    image: '/images/salar-de-uyuni.jpg',
    description: 'O maior deserto de sal do mundo. Reflexos de espelho na estação chuvosa, geometrias perfeitas na seca.',
    descriptionEs: 'El mayor desierto de sal del mundo. Reflejos de espejo en la época de lluvias, geometrías perfectas en la seca.',
    descriptionEn: 'The world\'s largest salt flat. Mirror reflections in the rainy season, perfect geometries in the dry season.',
    duration: '1 dia',
    availability: 'available',
    adults: 2,
    children: 0,
    badge: 'recommended',
    tags: ['natureza', 'aventura', 'fotografia'],
    includes: ['4x4', 'Guia', 'Almoço'],
    notIncludes: ['Hospedagem', 'Voos'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'transfer-aeroporto-atacama',
    slug: 'transfer-aeroporto-atacama',
    name: 'Transfer Aeroporto → San Pedro de Atacama',
    nameEs: 'Transfer Aeropuerto → San Pedro de Atacama',
    nameEn: 'Airport Transfer → San Pedro de Atacama',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'transfers',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'Transfer privativo do Aeroporto de Calama até San Pedro de Atacama com conforto e pontualidade.',
    descriptionEs: 'Transfer privado del Aeropuerto de Calama a San Pedro de Atacama con comodidad y puntualidad.',
    descriptionEn: 'Private transfer from Calama Airport to San Pedro de Atacama with comfort and punctuality.',
    duration: '1h30',
    availability: 'available',
    adults: 2,
    children: 0,
    tags: ['transfer', 'privativo'],
    includes: ['Veículo privativo', 'Motorista', 'Água mineral'],
    notIncludes: ['Gorjetas'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'atacama-essencial',
    slug: 'atacama-essencial',
    name: 'Atacama Essencial — 6 Dias / 5 Noites',
    nameEs: 'Atacama Esencial — 6 Días / 5 Noches',
    nameEn: 'Essential Atacama — 6 Days / 5 Nights',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'packages',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    description: 'Sinta a energia de um ecossistema único, onde a natureza e a imensidão do deserto se encontram.',
    descriptionEs: 'Siente la energía de un ecosistema único, donde la naturaleza y la inmensidad del desierto se encuentran.',
    descriptionEn: 'Feel the energy of a unique ecosystem, where nature and the immensity of the desert meet.',
    duration: '6 dias / 5 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'new',
    tags: ['pacote', 'roteiro', 'curadoria', 'atacama'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada no Atacama' },
      { day: 'Dia 02', title: 'Valle de la Luna' },
      { day: 'Dia 03', title: 'Geysers del Tatio' },
      { day: 'Dia 04', title: 'Lagunas Escondidas de Baltinache' },
      { day: 'Dia 05', title: 'Piedras Rojas e Lagunas Altiplânicas' },
      { day: 'Dia 06', title: 'Retorno' },
    ],
    includes: [
      'Valle de la Luna: Transporte, guia especializado, ingresso e coquetel',
      'Geysers del Tatio: Transporte, guia especializado e café da manhã',
      'Lagunas Escondidas de Baltinache: Transporte, guia especializado, café da manhã (turno manhã) ou coquetel (turno tarde)',
      'Piedras Rojas e Lagunas Altiplânicas: Transporte, guia especializado, ingressos',
    ],
    notIncludes: [
      'Transfer de saída ou retorno',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'cusco-vale-sagrado',
    slug: 'cusco-vale-sagrado',
    name: 'Cusco e Vale Sagrado',
    nameEs: 'Cusco y Valle Sagrado',
    nameEn: 'Cusco & Sacred Valley',
    destination: 'Cusco',
    country: 'Peru',
    category: 'tours',
    image: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
    description: 'Tour pelo coração do antigo Império Inca: Cusco histórico e as ruínas do Vale Sagrado em um dia completo.',
    descriptionEs: 'Tour por el corazón del antiguo Imperio Inca: Cusco histórico y las ruinas del Valle Sagrado en un día completo.',
    descriptionEn: 'Tour through the heart of the ancient Inca Empire: historic Cusco and the ruins of the Sacred Valley in a full day.',
    duration: '10 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    tags: ['cultura', 'história', 'arqueologia'],
    includes: ['Transporte', 'Guia bilíngue', 'Ingressos'],
    notIncludes: ['Almoço', 'Gorjetas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'tour-astronomico-atacama',
    slug: 'tour-astronomico-atacama',
    name: 'Tour Astronômico no Atacama',
    nameEs: 'Tour Astronómico en Atacama',
    nameEn: 'Atacama Stargazing Astronomy Tour',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'experiences',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    description: 'Observação do céu mais límpido do planeta com astrônomo, telescópios profissionais e astrofotografia inclusa.',
    descriptionEs: 'Observación del cielo más limpio del planeta con astrónomo, telescopios profesionales y astrofotografía incluida.',
    descriptionEn: 'Stargazing under the clearest skies on Earth with an astronomer, professional telescopes and astrophotography included.',
    duration: '2h30',
    availability: 'few-spots',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['astronomia', 'estrelas', 'noite'],
    includes: ['Transporte', 'Astrônomo guia', 'Telescópios profissionais', 'Foto de recordação', 'Bebida quente'],
    notIncludes: ['Roupas térmicas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'termas-de-puritama',
    slug: 'termas-de-puritama',
    name: 'Termas de Puritama & Canyon',
    nameEs: 'Termas de Puritama & Cañón',
    nameEn: 'Puritama Hot Springs & Canyon',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80',
    description: 'Banhos termais medicinais em piscinas naturais de águas quentes que correm pelo fundo de um deslumbrante cânion desértico.',
    descriptionEs: 'Baños termales medicinales en pozas naturales de aguas cálidas en el fondo de un cañón desértico.',
    descriptionEn: 'Medicinal thermal baths in natural pools of warm water running along the bottom of a stunning desert canyon.',
    duration: '4 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    badge: 'recommended',
    tags: ['relaxamento', 'natureza', 'bem-estar'],
    includes: ['Transporte ida e volta', 'Entrada às termas', 'Acesso aos vestiários'],
    notIncludes: ['Toalhas', 'Alimentação'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'transfer-cusco-hotel',
    slug: 'transfer-cusco-hotel',
    name: 'Transfer Aeroporto Cusco → Hotéis / Vale Sagrado',
    nameEs: 'Transfer Aeropuerto Cusco → Hoteles / Valle Sagrado',
    nameEn: 'Cusco Airport Transfer → Hotels / Sacred Valley',
    destination: 'Cusco',
    country: 'Peru',
    category: 'transfers',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    description: 'Recepção pontual no Aeroporto Alejandro Velasco Astete em Cusco e transporte privativo com todo o conforto até sua hospedagem.',
    descriptionEs: 'Recepción puntual en el Aeropuerto de Cusco y transporte privado con total comodidad hacia su hotel.',
    descriptionEn: 'Punctual meet & greet at Cusco Airport and private transfer in comfort to your hotel.',
    duration: '40min a 1h30',
    availability: 'available',
    adults: 2,
    children: 0,
    tags: ['transfer', 'aeroporto', 'privativo'],
    includes: ['Motorista bilíngue', 'Veículo climatizado', 'Monitoramento de voo', 'Água mineral'],
    notIncludes: ['Gorjetas'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'peru-magico-pacote',
    slug: 'peru-magico-pacote',
    name: 'Cores do Peru — 6 Dias / 5 Noites',
    nameEs: 'Colores del Perú — 6 Días / 5 Noches',
    nameEn: 'Colors of Peru — 6 Days / 5 Nights',
    destination: 'Cusco',
    country: 'Peru',
    category: 'packages',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'Sinta a energia de uma das culturas mais fascinantes do mundo em um itinerário planejado nos mínimos detalhes para transformar sua viagem em uma memória inesquecível.',
    descriptionEs: 'Siente la energía de una de las culturas más fascinantes del mundo en un itinerario planeado al detalle para transformar tu viaje en un recuerdo inolvidable.',
    descriptionEn: 'Feel the energy of one of the world’s most fascinating cultures in an itinerary planned down to the last detail to turn your trip into an unforgettable memory.',
    duration: '6 dias / 5 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['pacote', 'história', 'machu-picchu', 'peru'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Cusco e transfer para o hotel' },
      { day: 'Dia 02', title: 'Vale Sagrado dos Incas com conexão para Machu Picchu' },
      { day: 'Dia 03', title: 'Machu Picchu' },
      { day: 'Dia 04', title: 'Chinchero, Maras e Moray' },
      { day: 'Dia 05', title: 'Montanha Colorida' },
      { day: 'Dia 06', title: 'Transfer de saída' },
    ],
    includes: [
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'Vale Sagrado: Transporte, guia especializado e almoço',
      'Machu Picchu: Todos os ingressos, passagens de trem e guia privativo em português',
      'Chinchero, Maras e Moray: Transporte, guia especializado e ingresso da salinera',
      'Montanha Colorida: Transporte, guia, café da manhã, almoço e ingresso',
    ],
    notIncludes: [
      'Boleto Turístico de Cusco',
      'Alimentação não mencionada no itinerário',
      'Aluguel de cavalos',
      'Passagens aéreas',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'cusco-light-pacote',
    slug: 'cusco-light',
    name: 'Cusco Light — 6 Dias / 5 Noites',
    nameEs: 'Cusco Light — 6 Días / 5 Noches',
    nameEn: 'Cusco Light — 6 Days / 5 Nights',
    destination: 'Cusco',
    country: 'Peru',
    category: 'packages',
    image: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
    description: 'Descubra a magia do Império Inca em um roteiro essencial, unindo história, cultura viva e a inesquecível cidadela de Machu Picchu no seu próprio ritmo.',
    descriptionEs: 'Descubre la magia del Imperio Inca en un itinerario esencial, uniendo historia, cultura viva y la inolvidable ciudadela de Machu Picchu a tu propio ritmo.',
    descriptionEn: 'Discover the magic of the Inca Empire in an essential itinerary, combining history, living culture and the unforgettable citadel of Machu Picchu at your own pace.',
    duration: '6 dias / 5 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'história', 'machu-picchu', 'peru'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Cusco e transfer para o hotel' },
      { day: 'Dia 02', title: 'City Tour Arqueológico' },
      { day: 'Dia 03', title: 'Vale Sagrado dos Incas com conexão para Machu Picchu' },
      { day: 'Dia 04', title: 'Machu Picchu' },
      { day: 'Dia 05', title: 'Ponte Inca Qeswachaka' },
      { day: 'Dia 06', title: 'Transfer de saída' },
    ],
    includes: [
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'City Tour: Transporte, guia e ingresso para o Qorikancha',
      'Vale Sagrado: Transporte, guia especializado e almoço',
      'Machu Picchu: Todos os ingressos, passagens de trem e guia privativo em português',
      'Ponte Qeswachaka: Transporte, guia, café da manhã, almoço e ingresso',
    ],
    notIncludes: [
      'Boleto Turístico de Cusco',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'aventura-andina-pacote',
    slug: 'aventura-andina',
    name: 'Aventura Andina — 8 Dias / 7 Noites',
    nameEs: 'Aventura Andina — 8 Días / 7 Noches',
    nameEn: 'Andean Adventure — 8 Days / 7 Nights',
    destination: 'Lima & Cusco',
    country: 'Peru',
    category: 'packages',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'Viva uma experiência transformadora entre tradições milenares, vales sagrados e grandes monumentos históricos, garantindo o equilíbrio perfeito entre aventura e descanso.',
    descriptionEs: 'Vive una experiencia transformadora entre tradiciones milenarias, valles sagrados y grandes monumentos históricos, con el equilibrio perfecto entre aventura y descanso.',
    descriptionEn: 'Live a transformative experience among ancient traditions, sacred valleys and great historical monuments, with the perfect balance between adventure and rest.',
    duration: '8 dias / 7 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'new',
    tags: ['pacote', 'história', 'machu-picchu', 'peru', 'lima'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Lima e transfer para o hotel' },
      { day: 'Dia 02', title: 'City Tour em Lima' },
      { day: 'Dia 03', title: 'Paracas e Huacachina' },
      { day: 'Dia 04', title: 'Saída de Lima para Cusco' },
      { day: 'Dia 05', title: 'Vale Sagrado VIP' },
      { day: 'Dia 06', title: 'Machu Picchu' },
      { day: 'Dia 07', title: 'Montanha Colorida' },
      { day: 'Dia 08', title: 'Transfer de saída' },
    ],
    includes: [
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'City Tour em Lima: Transporte, guia especializado e ingressos',
      'Paracas e Huacachina: Transporte, guia especializado e ingressos',
      'Vale Sagrado VIP: Transporte, guia especializado, almoço e ingresso da salinera',
      'Machu Picchu: Todos os ingressos, passagens de trem e guia privativo em português',
      'Montanha Colorida: Transporte, guia, café da manhã, almoço e ingresso',
    ],
    notIncludes: [
      'Boleto Turístico de Cusco',
      'Alimentação não mencionada no itinerário',
      'Aluguel de cavalos',
      'Passagens aéreas',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'lima-huaraz-pacote',
    slug: 'lima-huaraz',
    name: 'Lima e Huaraz — 8 Dias / 7 Noites',
    nameEs: 'Lima y Huaraz — 8 Días / 7 Noches',
    nameEn: 'Lima & Huaraz — 8 Days / 7 Nights',
    destination: 'Lima & Huaraz',
    country: 'Peru',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Uma imersão fascinante entre tradições milenares e cenários deslumbrantes no seu próprio ritmo.',
    descriptionEs: 'Una inmersión fascinante entre tradiciones milenarias y paisajes deslumbrantes a tu propio ritmo.',
    descriptionEn: 'A fascinating immersion among ancient traditions and stunning landscapes at your own pace.',
    duration: '8 dias / 7 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'natureza', 'trekking', 'peru', 'lima'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Lima e transfer para o hotel' },
      { day: 'Dia 02', title: 'Paracas e Huacachina' },
      { day: 'Dia 03', title: 'City Tour em Lima' },
      { day: 'Dia 04', title: 'Viagem para Huaraz, transfer de saída de Lima e chegada em Huaraz' },
      { day: 'Dia 05', title: 'Nevado Pastoruri' },
      { day: 'Dia 06', title: 'Laguna Rocotuyoc' },
      { day: 'Dia 07', title: 'Laguna 69' },
      { day: 'Dia 08', title: 'Transfer de saída' },
    ],
    includes: [
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'Paracas e Huacachina: Transporte, guia especializado e ingressos',
      'City Tour em Lima: Transporte, guia especializado e ingressos',
      'Nevado Pastoruri: Transporte, guia especializado, ingressos',
      'Laguna Rocotuyoc: Transporte, guia especializado, ingressos',
      'Laguna 69: Transporte, guia especializado, ingressos',
    ],
    notIncludes: [
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Bastões de trekking (pode ser alugado na praça central de Huaraz)',
      'Aluguel de cavalos',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'santiago-encantador-pacote',
    slug: 'santiago-encantador',
    name: 'Santiago Encantador — 5 Dias / 4 Noites',
    nameEs: 'Santiago Encantador — 5 Días / 4 Noches',
    nameEn: 'Charming Santiago — 5 Days / 4 Nights',
    destination: 'Santiago',
    country: 'Chile',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Viva a sofisticação da capital chilena entre a Cordilheira dos Andes e cenários urbanos inesquecíveis.',
    descriptionEs: 'Vive la sofisticación de la capital chilena entre la Cordillera de los Andes y escenarios urbanos inolvidables.',
    descriptionEn: 'Experience the sophistication of the Chilean capital between the Andes mountain range and unforgettable urban scenery.',
    duration: '5 dias / 4 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'chile', 'santiago', 'vinícola'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Santiago' },
      { day: 'Dia 02', title: 'Visita a Vinícola' },
      { day: 'Dia 03', title: 'Portillo e Laguna del Inca' },
      { day: 'Dia 04', title: 'Viña del Mar e Valparaíso' },
      { day: 'Dia 05', title: 'Retorno' },
    ],
    includes: [
      'Vinícola: Transporte, guia especializado e degustação de vinhos',
      'Portillo e Laguna del Inca: Transporte, guia especializado, picnic',
      'Viña del Mar e Valparaíso: Transporte, guia especializado',
    ],
    notIncludes: [
      'Transfer de saída ou retorno',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'santiago-premium-pacote',
    slug: 'santiago-premium',
    name: 'Santiago Premium — 6 Dias / 5 Noites',
    nameEs: 'Santiago Premium — 6 Días / 5 Noches',
    nameEn: 'Santiago Premium — 6 Days / 5 Nights',
    destination: 'Santiago',
    country: 'Chile',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Descubra o charme, a gastronomia e as paisagens mais impressionantes do Chile em uma experiência única.',
    descriptionEs: 'Descubre el encanto, la gastronomía y los paisajes más impresionantes de Chile en una experiencia única.',
    descriptionEn: 'Discover the charm, gastronomy and most impressive landscapes of Chile in a unique experience.',
    duration: '6 dias / 5 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'chile', 'santiago', 'vinícola'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Santiago' },
      { day: 'Dia 02', title: 'Vinícola Aylan Sunset' },
      { day: 'Dia 03', title: 'Cajón del Maipo e Embalse el Yeso' },
      { day: 'Dia 04', title: 'Viña del Mar e Valparaíso' },
      { day: 'Dia 05', title: 'Portillo e Laguna del Inca' },
      { day: 'Dia 06', title: 'Retorno' },
    ],
    includes: [
      'Vinícola Aylan Sunset: Transporte, guia especializado, 6 tipos de degustação de vinhos (servidos à vontade), petiscos selecionados, jantar completo e sobremesa',
      'Cajón del Maipo e Embalse el Yeso: Transporte, guia especializado e picnic',
      'Viña del Mar e Valparaíso: Transporte, guia especializado',
      'Portillo e Laguna del Inca: Transporte, guia especializado, picnic',
    ],
    notIncludes: [
      'Transfer de saída ou retorno',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'atacama-uyuni-pacote',
    slug: 'atacama-salar-uyuni',
    name: 'Atacama e Salar do Uyuni — 7 Dias / 6 Noites',
    nameEs: 'Atacama y Salar de Uyuni — 7 Días / 6 Noches',
    nameEn: 'Atacama & Salar de Uyuni — 7 Days / 6 Nights',
    destination: 'San Pedro de Atacama & Uyuni',
    country: 'Chile',
    category: 'packages',
    image: '/images/salar-de-uyuni.jpg',
    description: 'Conecte-se com a força da natureza em um roteiro fascinante que une vulcões, lagoas coloridas e o deserto de sal.',
    descriptionEs: 'Conéctate con la fuerza de la naturaleza en un itinerario fascinante que une volcanes, lagunas de colores y el desierto de sal.',
    descriptionEn: 'Connect with the power of nature on a fascinating route that joins volcanoes, colorful lagoons and the salt desert.',
    duration: '7 dias / 6 noites',
    availability: 'few-spots',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['pacote', 'expedição', 'atacama', 'uyuni', 'bolívia'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada no Atacama' },
      { day: 'Dia 02', title: 'Valle de la Luna' },
      { day: 'Dia 03', title: 'Piedras Rojas e Lagunas Altiplânicas' },
      { day: 'Dia 04', title: 'Saída para a Bolívia (dia 1): Mirante Laguna Blanca, Mirante Laguna Verde, Deserto Dalí, Fontes Termais de Polques, Gêiseres Sol de Mañana, Mirante Laguna Colorada e Mirante Laguna Capina' },
      { day: 'Dia 05', title: 'Bolívia (dia 2): Laguna de Vinto, Laguna Misteriosa, Grand Canyon da Anaconda, Bofedales de Sora e a cidade abandonada de Juliaca' },
      { day: 'Dia 06', title: 'Bolívia (dia 3): Ilha Incahuasi, Salar de Uyuni, Museu das Bandeiras, Feira de Artesanato em Colchani, Cemitério de Trens de Uyuni' },
      { day: 'Dia 07', title: 'Bolívia (dia 4): Retorno ao Atacama' },
    ],
    includes: [
      'Valle de la Luna: Transporte, guia especializado, ingresso e coquetel',
      'Piedras Rojas e Lagunas Altiplânicas: Transporte, guia especializado, ingressos',
      'Bolívia: Transporte ida e volta, guia bilíngue, alimentação durante os 4 dias, alojamento em hostel (quarto privativo ou compartilhado), fotos e vídeos durante o passeio',
    ],
    notIncludes: [
      'Transfer de saída ou retorno',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem no Atacama',
      'Ingressos na Bolívia (250 bolivianos)',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'buenos-aires-express-pacote',
    slug: 'buenos-aires-express',
    name: 'Buenos Aires Express — 4 Dias / 3 Noites',
    nameEs: 'Buenos Aires Express — 4 Días / 3 Noches',
    nameEn: 'Buenos Aires Express — 4 Days / 3 Nights',
    destination: 'Buenos Aires',
    country: 'Argentina',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Encante-se com o charme europeu, a gastronomia marcante e a paixão pelo tango no coração da Argentina.',
    descriptionEs: 'Déjate encantar por el estilo europeo, la gastronomía marcante y la pasión por el tango en el corazón de Argentina.',
    descriptionEn: 'Be charmed by the European style, standout cuisine and passion for tango in the heart of Argentina.',
    duration: '4 dias / 3 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'argentina', 'buenos-aires', 'tango'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Buenos Aires e transfer para o hotel' },
      { day: 'Dia 02', title: 'City Tour Histórico e Cultural e Noite de Show de Tango' },
      { day: 'Dia 03', title: 'Passeio Delta e Tigre' },
      { day: 'Dia 04', title: 'Transfer de retorno' },
    ],
    includes: [
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'City Tour: Transporte, guia especializado',
      'Delta e Tigre: Transporte, guia especializado, navegação em barco catamarã',
    ],
    notIncludes: [
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'buenos-aires-mendoza-pacote',
    slug: 'buenos-aires-mendoza-premium',
    name: 'Buenos Aires & Mendoza Premium — 6 Dias / 5 Noites',
    nameEs: 'Buenos Aires & Mendoza Premium — 6 Días / 5 Noches',
    nameEn: 'Buenos Aires & Mendoza Premium — 6 Days / 5 Nights',
    destination: 'Buenos Aires & Mendoza',
    country: 'Argentina',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Uma experiência completa unindo a energia vibrante da capital argentina e o encanto dos vinhedos aos pés da Cordilheira dos Andes.',
    descriptionEs: 'Una experiencia completa que une la energía vibrante de la capital argentina y el encanto de los viñedos a los pies de la Cordillera de los Andes.',
    descriptionEn: 'A complete experience combining the vibrant energy of the Argentine capital and the charm of the vineyards at the foot of the Andes.',
    duration: '6 dias / 5 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'argentina', 'buenos-aires', 'mendoza', 'vinícola'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Buenos Aires e transfer para o hotel' },
      { day: 'Dia 02', title: 'City Tour Histórico e Cultural e Noite de Show de Tango' },
      { day: 'Dia 03', title: 'Voo para Mendoza e transfer para o hotel' },
      { day: 'Dia 04', title: 'Tour vinhos e oliva' },
      { day: 'Dia 05', title: 'Tour Parque Aconcágua' },
      { day: 'Dia 06', title: 'Transfer de retorno' },
    ],
    includes: [
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'City Tour: Transporte, guia especializado',
      'Tour vinhos e oliva: Transporte, guia especializado, degustação',
      'Tour Parque Aconcágua: Transporte, guia especializado, box lunch',
    ],
    notIncludes: [
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'colombia-caribenha-pacote',
    slug: 'colombia-caribenha',
    name: 'Colômbia Caribenha — 7 Dias / 6 Noites',
    nameEs: 'Colombia Caribeña — 7 Días / 6 Noches',
    nameEn: 'Caribbean Colombia — 7 Days / 6 Nights',
    destination: 'Cartagena & San Andrés',
    country: 'Colômbia',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Uma imersão inesquecível entre o centro histórico colonial de Cartagena e as águas cristalinas do arquipélago de San Andrés.',
    descriptionEs: 'Una inmersión inolvidable entre el centro histórico colonial de Cartagena y las aguas cristalinas del archipiélago de San Andrés.',
    descriptionEn: 'An unforgettable immersion between Cartagena’s colonial old town and the crystal-clear waters of the San Andrés archipelago.',
    duration: '7 dias / 6 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'colômbia', 'cartagena', 'praia'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Cartagena' },
      { day: 'Dia 02', title: 'City Tour Histórico por Cartagena e Castelo de San Felipe' },
      { day: 'Dia 03', title: 'Passeio de barco para as Islas del Rosario' },
      { day: 'Dia 04', title: 'Voo para San Andrés' },
      { day: 'Dia 05', title: 'Tour de barco Johnny Cay' },
      { day: 'Dia 06', title: 'Volta à ilha e dia livre para aproveitar as praias' },
      { day: 'Dia 07', title: 'Retorno' },
    ],
    includes: [
      'City Tour: Transporte em carro climatizado, guia bilíngue espanhol e inglês, entrada no Castillo San Felipe, walking tour pelo centro histórico',
      'Islas del Rosario: Transporte de lancha ida e regresso, acesso à ilha, cama de praia ou espreguiçadeiras, 1 coquetel de boas-vindas, almoço',
      'Johnny Cay: Transporte em lancha ida e regresso, visitação em Johnny Cay',
    ],
    notIncludes: [
      'Transporte até o ponto de saída dos passeios, taxas portuárias',
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Espanhol', 'Inglês'],
  },
  {
    id: 'bogota-medellin-pacote',
    slug: 'bogota-medellin-essencial',
    name: 'Bogotá & Medellín Essencial — 7 Dias / 6 Noites',
    nameEs: 'Bogotá & Medellín Esencial — 7 Días / 6 Noches',
    nameEn: 'Bogotá & Medellín Essential — 7 Days / 6 Nights',
    destination: 'Bogotá & Medellín',
    country: 'Colômbia',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Descubra a vibração cultural, a rica história e a impressionante transformação urbana de duas das capitais mais fascinantes da América do Sul.',
    descriptionEs: 'Descubre la vibración cultural, la rica historia y la impresionante transformación urbana de dos de las capitales más fascinantes de Sudamérica.',
    descriptionEn: 'Discover the cultural vibrancy, rich history and impressive urban transformation of two of South America’s most fascinating capitals.',
    duration: '7 dias / 6 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'colômbia', 'bogotá', 'medellín'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em Bogotá' },
      { day: 'Dia 02', title: 'Walking Tour Privativo' },
      { day: 'Dia 03', title: 'Tour Catedral de Sal Fast Pass' },
      { day: 'Dia 04', title: 'Voo para Medellín' },
      { day: 'Dia 05', title: 'Tour Guatapé com Peñol' },
      { day: 'Dia 06', title: 'City Tour com Comuna 13' },
      { day: 'Dia 07', title: 'Retorno' },
    ],
    includes: [
      'Walking Tour Privativo: Guia privativo em espanhol',
      'Tour Catedral de Sal Fast Pass: Transporte ida e volta desde o hotel, tempo livre de visita à Catedral',
      'Tour Guatapé com Peñol: Transporte desde ponto de encontro, almoço típico antioqueño, guia acompanhante em espanhol, visita ao povoado do Peñol (não inclui entrada), Calle de los Recuerdos',
      'City Tour com Comuna 13: Transporte ida e regresso desde ponto de encontro, guia acompanhante em espanhol, visita ao Pueblito Paisa, Plaza Botero, Parque de los Pies Descalzos, Parque del Río, Metro, MetroCable, Comuna 13 e escadas elétricas, entrada de Metro e MetroCable, almoço típico',
    ],
    notIncludes: [
      'Transporte até o ponto de encontro',
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Espanhol'],
  },
  {
    id: 'la-paz-valle-luna-pacote',
    slug: 'la-paz-valle-de-la-luna',
    name: 'La Paz & Valle de la Luna — 4 Dias / 3 Noites',
    nameEs: 'La Paz & Valle de la Luna — 4 Días / 3 Noches',
    nameEn: 'La Paz & Valley of the Moon — 4 Days / 3 Nights',
    destination: 'La Paz',
    country: 'Bolívia',
    category: 'packages',
    image: '/images/hero-principal.jpg',
    description: 'Descubra a vibração cultural, a rica história e a paisagem única da capital mais alta do mundo.',
    descriptionEs: 'Descubre la vibración cultural, la rica historia y el paisaje único de la capital más alta del mundo.',
    descriptionEn: 'Discover the cultural vibrancy, rich history and unique scenery of the world’s highest capital.',
    duration: '4 dias / 3 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'bolívia', 'la-paz'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em La Paz' },
      { day: 'Dia 02', title: 'City Tour meio dia com teleférico' },
      { day: 'Dia 03', title: 'Tour Valle de las Ánimas' },
      { day: 'Dia 04', title: 'Retorno' },
    ],
    includes: [
      'City Tour: Transporte panorâmico, guia bilíngue, ingresso do teleférico',
      'Tour Valle de las Ánimas: Transporte, guia',
    ],
    notIncludes: [
      'Entrada para o Valle de la Luna no city tour',
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'la-paz-uyuni-express-pacote',
    slug: 'la-paz-salar-uyuni-express',
    name: 'La Paz & Salar de Uyuni Express — 6 Dias / 5 Noites',
    nameEs: 'La Paz & Salar de Uyuni Express — 6 Días / 5 Noches',
    nameEn: 'La Paz & Salar de Uyuni Express — 6 Days / 5 Nights',
    destination: 'La Paz & Uyuni',
    country: 'Bolívia',
    category: 'packages',
    image: '/images/salar-de-uyuni.jpg',
    description: 'Descubra a vibração cultural da capital mais alta do mundo e o deslumbrante deserto de sal de Uyuni em um único roteiro.',
    descriptionEs: 'Descubre la vibración cultural de la capital más alta del mundo y el deslumbrante desierto de sal de Uyuni en un solo itinerario.',
    descriptionEn: 'Discover the cultural vibrancy of the world’s highest capital and the stunning Uyuni salt desert in a single itinerary.',
    duration: '6 dias / 5 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['pacote', 'bolívia', 'la-paz', 'uyuni'],
    itinerary: [
      { day: 'Dia 01', title: 'Chegada em La Paz' },
      { day: 'Dia 02', title: 'Dia livre em La Paz para compras ou passeios opcionais' },
      { day: 'Dia 03', title: 'City Tour meio dia com teleférico' },
      { day: 'Dia 04', title: 'Voo para o Uyuni' },
      { day: 'Dia 05', title: 'Full Day no Salar de Uyuni' },
      { day: 'Dia 06', title: 'Retorno' },
    ],
    includes: [
      'City Tour: Transporte panorâmico, guia bilíngue, ingresso do teleférico',
      'Tour Salar de Uyuni: Transporte 4x4, almoço, guia, oxigênio e vinho',
    ],
    notIncludes: [
      'Transfers de chegada e saída (Aeroporto / Hotel / Aeroporto)',
      'Alimentação não mencionada no itinerário',
      'Passagens aéreas e ônibus de deslocamento',
      'Hospedagem',
    ],
    closingTitle: 'Gostou deste pacote?',
    closingText: 'Prefere um roteiro 100% personalizado para a sua viagem? Fale com a nossa equipe agora mesmo pelo WhatsApp!',
    ctaLabel: 'Falar no WhatsApp',
    languages: ['Português', 'Espanhol'],
  },
];

export const destinations = [
  {
    id: 'peru',
    name: 'Peru',
    slug: 'peru',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'Civilizações, mistérios e natureza.',
    productCount: sampleProducts.filter((p) => p.country === 'Peru').length,
  },
  {
    id: 'chile',
    name: 'Chile',
    slug: 'chile',
    image: '/images/valle-de-la-luna.jpg',
    description: 'Do deserto ao fim do mundo.',
    productCount: sampleProducts.filter((p) => p.country === 'Chile').length,
  },
  {
    id: 'bolivia',
    name: 'Bolívia',
    slug: 'bolivia',
    image: '/images/salar-de-uyuni.jpg',
    description: 'O salar mais incrível da terra.',
    productCount: sampleProducts.filter((p) => p.country === 'Bolívia').length,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    slug: 'argentina',
    image: '/images/patagonia-argentina.jpg',
    description: 'Patagônia, vinhos e tango.',
    productCount: sampleProducts.filter((p) => p.country === 'Argentina').length,
  },
  {
    id: 'colombia',
    name: 'Colômbia',
    slug: 'colombia',
    image: '/images/hero-principal.jpg',
    description: 'Caribe, café e cidades vibrantes.',
    productCount: sampleProducts.filter((p) => p.country === 'Colômbia').length,
  },
];
