import { TripItem, AvailabilityStatus } from '@/lib/store';

export interface Product extends TripItem {
  description: string;
  descriptionEs?: string;
  descriptionEn?: string;
  fullDescription?: string;
  includes?: string[];
  notIncludes?: string[];
  whatToBring?: string[];
  meetingPoint?: string;
  importantInfo?: string;
  schedule?: string;
  minPeople?: number;
  maxPeople?: number;
  languages?: string[];
  tags?: string[];
  gallery?: string[];
  featured?: boolean;
  badge?: 'popular' | 'new' | 'recommended' | 'sale';
  relatedProducts?: string[];
  priceChild?: number;
  priceSale?: number;
}

export const sampleProducts: Product[] = [
  {
    id: 'valle-de-la-luna',
    slug: 'valle-de-la-luna',
    name: 'Valle de la Luna & Miradores',
    nameEs: 'Valle de la Luna & Miradores',
    nameEn: 'Valley of the Moon & Viewpoints',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: '/images/valle-de-la-luna.jpg',
    gallery: [
      '/images/valle-de-la-luna.jpg',
      '/images/hero-principal.jpg',
    ],
    description: 'Um dos cenários mais surreais do Atacama. Formações de sal, crateras e cores que mudam com a luz do entardecer.',
    descriptionEs: 'Uno de los paisajes más surrealistas del Atacama. Formaciones de sal, cráteres y colores que cambian con la luz del atardecer.',
    descriptionEn: 'One of the most surreal landscapes in the Atacama. Salt formations, craters and colors that change with the evening light.',
    duration: '5 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    price: undefined,
    featured: true,
    badge: 'popular',
    tags: ['natureza', 'cultura', 'pôr-do-sol'],
    includes: ['Transporte', 'Guia local', 'Entrada ao parque'],
    notIncludes: ['Alimentação', 'Gorjetas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'lagunas-altiplanicas',
    slug: 'lagunas-altiplanicas',
    name: 'Lagunas Altiplânicas',
    nameEs: 'Lagunas Altiplánicas',
    nameEn: 'Altiplanic Lagoons',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: 'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=800&q=80',
    description: 'Lagoas de altitude com flamingos e paisagens de outro mundo. Um espetáculo da natureza altiplânica.',
    descriptionEs: 'Lagunas de altura con flamencos y paisajes de otro mundo. Un espectáculo de la naturaleza altiplánica.',
    descriptionEn: 'High-altitude lagoons with flamingos and otherworldly landscapes. A natural spectacle of the altiplano.',
    duration: '8 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'recommended',
    tags: ['natureza', 'aventura', 'fauna'],
    includes: ['Transporte 4x4', 'Guia', 'Box lunch'],
    notIncludes: ['Gorjetas', 'Bebidas extras'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'geysers-del-tatio',
    slug: 'geysers-del-tatio',
    name: 'Geysers del Tatio',
    nameEs: 'Géiseres del Tatio',
    nameEn: 'El Tatio Geysers',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: '/images/geysers-del-tatio.jpg',
    description: 'Campo de geysers a 4.320m de altitude. Um espetáculo geotérmico ao amanhecer no coração do Atacama.',
    descriptionEs: 'Campo de géiseres a 4.320m de altitud. Un espectáculo geotérmico al amanecer en el corazón del Atacama.',
    descriptionEn: 'Geyser field at 4,320m altitude. A geothermal spectacle at dawn in the heart of the Atacama.',
    duration: '6 horas',
    availability: 'few-spots',
    adults: 2,
    children: 0,
    featured: true,
    tags: ['natureza', 'aventura', 'madrugada'],
    includes: ['Transporte', 'Guia', 'Café da manhã'],
    notIncludes: ['Seguro viagem', 'Gorjetas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'machu-picchu-day',
    slug: 'machu-picchu-day',
    name: 'Machu Picchu — Dia Completo',
    nameEs: 'Machu Picchu — Día Completo',
    nameEn: 'Machu Picchu — Full Day',
    destination: 'Cusco',
    country: 'Peru',
    category: 'experiences',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'A cidade perdida dos Incas em toda sua magnitude. Tour completo com guia especializado e trem turístico.',
    descriptionEs: 'La ciudad perdida de los Incas en toda su magnitud. Tour completo con guía especializado y tren turístico.',
    descriptionEn: 'The lost city of the Incas in all its magnitude. Complete tour with specialized guide and tourist train.',
    duration: '12 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['cultura', 'história', 'patrimônio'],
    includes: ['Trem de ida e volta', 'Ingresso Machu Picchu', 'Guia'],
    notIncludes: ['Alimentação', 'Ônibus subida/descida opcional'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'salar-de-uyuni',
    slug: 'salar-de-uyuni',
    name: 'Salar de Uyuni — Tour Clássico',
    nameEs: 'Salar de Uyuni — Tour Clásico',
    nameEn: 'Salar de Uyuni — Classic Tour',
    destination: 'Uyuni',
    country: 'Bolívia',
    category: 'tours',
    image: '/images/salar-de-uyuni.jpg',
    description: 'O maior deserto de sal do mundo. Reflexos de espelho na estação chuvosa, geometrias perfeitas na seca.',
    descriptionEs: 'El mayor desierto de sal del mundo. Reflejos de espejo en la época de lluvias, geometrías perfectas en la seca.',
    descriptionEn: 'The world\'s largest salt flat. Mirror reflections in the rainy season, perfect geometries in the dry season.',
    duration: '1 dia',
    availability: 'available',
    adults: 2,
    children: 0,
    badge: 'recommended',
    tags: ['natureza', 'aventura', 'fotografia'],
    includes: ['4x4', 'Guia', 'Almoço'],
    notIncludes: ['Hospedagem', 'Voos'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'transfer-aeroporto-atacama',
    slug: 'transfer-aeroporto-atacama',
    name: 'Transfer Aeroporto → San Pedro de Atacama',
    nameEs: 'Transfer Aeropuerto → San Pedro de Atacama',
    nameEn: 'Airport Transfer → San Pedro de Atacama',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'transfers',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'Transfer privativo do Aeroporto de Calama até San Pedro de Atacama com conforto e pontualidade.',
    descriptionEs: 'Transfer privado del Aeropuerto de Calama a San Pedro de Atacama con comodidad y puntualidad.',
    descriptionEn: 'Private transfer from Calama Airport to San Pedro de Atacama with comfort and punctuality.',
    duration: '1h30',
    availability: 'available',
    adults: 2,
    children: 0,
    tags: ['transfer', 'privativo'],
    includes: ['Veículo privativo', 'Motorista', 'Água mineral'],
    notIncludes: ['Gorjetas'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'atacama-essencial',
    slug: 'atacama-essencial',
    name: 'Atacama Essencial — 5 Dias',
    nameEs: 'Atacama Esencial — 5 Días',
    nameEn: 'Essential Atacama — 5 Days',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'packages',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    description: 'Roteiro completo pelo Deserto do Atacama com os principais atrativos, transfer, passeios e curadoria completa.',
    descriptionEs: 'Itinerario completo por el Desierto de Atacama con los principales atractivos, transfer, paseos y curaduría completa.',
    descriptionEn: 'Complete itinerary through the Atacama Desert with the main attractions, transfers, tours and full curation.',
    duration: '5 dias / 4 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'new',
    tags: ['pacote', 'roteiro', 'curadoria'],
    includes: ['Transfer aeroporto', 'Hospedagem', 'Valle de la Luna', 'Lagunas Altiplânicas', 'Geysers del Tatio'],
    notIncludes: ['Passagem aérea', 'Refeições não listadas'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'cusco-vale-sagrado',
    slug: 'cusco-vale-sagrado',
    name: 'Cusco e Vale Sagrado',
    nameEs: 'Cusco y Valle Sagrado',
    nameEn: 'Cusco & Sacred Valley',
    destination: 'Cusco',
    country: 'Peru',
    category: 'tours',
    image: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
    description: 'Tour pelo coração do antigo Império Inca: Cusco histórico e as ruínas do Vale Sagrado em um dia completo.',
    descriptionEs: 'Tour por el corazón del antiguo Imperio Inca: Cusco histórico y las ruinas del Valle Sagrado en un día completo.',
    descriptionEn: 'Tour through the heart of the ancient Inca Empire: historic Cusco and the ruins of the Sacred Valley in a full day.',
    duration: '10 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    tags: ['cultura', 'história', 'arqueologia'],
    includes: ['Transporte', 'Guia bilíngue', 'Ingressos'],
    notIncludes: ['Almoço', 'Gorjetas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'tour-astronomico-atacama',
    slug: 'tour-astronomico-atacama',
    name: 'Tour Astronômico no Atacama',
    nameEs: 'Tour Astronómico en Atacama',
    nameEn: 'Atacama Stargazing Astronomy Tour',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'experiences',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    description: 'Observação do céu mais límpido do planeta com astrônomo, telescópios profissionais e astrofotografia inclusa.',
    descriptionEs: 'Observación del cielo más limpio del planeta con astrónomo, telescopios profesionales y astrofotografía incluida.',
    descriptionEn: 'Stargazing under the clearest skies on Earth with an astronomer, professional telescopes and astrophotography included.',
    duration: '2h30',
    availability: 'few-spots',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['astronomia', 'estrelas', 'noite'],
    includes: ['Transporte', 'Astrônomo guia', 'Telescópios profissionais', 'Foto de recordação', 'Bebida quente'],
    notIncludes: ['Roupas térmicas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'termas-de-puritama',
    slug: 'termas-de-puritama',
    name: 'Termas de Puritama & Canyon',
    nameEs: 'Termas de Puritama & Cañón',
    nameEn: 'Puritama Hot Springs & Canyon',
    destination: 'San Pedro de Atacama',
    country: 'Chile',
    category: 'tours',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80',
    description: 'Banhos termais medicinais em piscinas naturais de águas quentes que correm pelo fundo de um deslumbrante cânion desértico.',
    descriptionEs: 'Baños termales medicinales en pozas naturales de aguas cálidas en el fondo de un cañón desértico.',
    descriptionEn: 'Medicinal thermal baths in natural pools of warm water running along the bottom of a stunning desert canyon.',
    duration: '4 horas',
    availability: 'available',
    adults: 2,
    children: 0,
    badge: 'recommended',
    tags: ['relaxamento', 'natureza', 'bem-estar'],
    includes: ['Transporte ida e volta', 'Entrada às termas', 'Acesso aos vestiários'],
    notIncludes: ['Toalhas', 'Alimentação'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'transfer-cusco-hotel',
    slug: 'transfer-cusco-hotel',
    name: 'Transfer Aeroporto Cusco → Hotéis / Vale Sagrado',
    nameEs: 'Transfer Aeropuerto Cusco → Hoteles / Valle Sagrado',
    nameEn: 'Cusco Airport Transfer → Hotels / Sacred Valley',
    destination: 'Cusco',
    country: 'Peru',
    category: 'transfers',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    description: 'Recepção pontual no Aeroporto Alejandro Velasco Astete em Cusco e transporte privativo com todo o conforto até sua hospedagem.',
    descriptionEs: 'Recepción puntual en el Aeropuerto de Cusco y transporte privado con total comodidad hacia su hotel.',
    descriptionEn: 'Punctual meet & greet at Cusco Airport and private transfer in comfort to your hotel.',
    duration: '40min a 1h30',
    availability: 'available',
    adults: 2,
    children: 0,
    tags: ['transfer', 'aeroporto', 'privativo'],
    includes: ['Motorista bilíngue', 'Veículo climatizado', 'Monitoramento de voo', 'Água mineral'],
    notIncludes: ['Gorjetas'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'peru-magico-pacote',
    slug: 'peru-magico-pacote',
    name: 'Peru Mágico: Cusco, Vale Sagrado & Machu Picchu — 6 Dias',
    nameEs: 'Perú Mágico: Cusco, Valle Sagrado & Machu Picchu — 6 Días',
    nameEn: 'Magical Peru: Cusco, Sacred Valley & Machu Picchu — 6 Days',
    destination: 'Cusco',
    country: 'Peru',
    category: 'packages',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'O pacote definitivo pelo Império Inca: hospedagens charmosas, ingressos para Machu Picchu, trem panorâmico e guias privativos.',
    descriptionEs: 'El paquete definitivo por el Imperio Inca: hoteles con encanto, entradas a Machu Picchu, tren panorámico y guías privados.',
    descriptionEn: 'The definitive Inca Empire package: charming hotels, Machu Picchu tickets, scenic train and private guides.',
    duration: '6 dias / 5 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['pacote', 'história', 'machu-picchu', 'peru'],
    includes: ['Transfers aeroporto', 'Hospedagem 5 noites', 'City Tour Cusco', 'Vale Sagrado com almoço', 'Trem Vistadome', 'Ingresso Machu Picchu com guia'],
    notIncludes: ['Voos internacionais', 'Seguro viagem'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
  {
    id: 'expedicao-uyuni-4dias',
    slug: 'expedicao-uyuni-4dias',
    name: 'Expedição Salar de Uyuni & Lagunas Coloradas — 4 Dias',
    nameEs: 'Expedición Salar de Uyuni & Lagunas Coloradas — 4 Días',
    nameEn: 'Salar de Uyuni & Colored Lagoons Expedition — 4 Days',
    destination: 'Uyuni',
    country: 'Bolívia',
    category: 'packages',
    image: '/images/salar-de-uyuni.jpg',
    description: 'Travessia em 4x4 entre San Pedro de Atacama e Uyuni, passando pelo Salar, Laguna Colorada com flamingos e Geysers Sol de Mañana.',
    descriptionEs: 'Travesía en 4x4 entre San Pedro de Atacama y Uyuni, visitando el Salar, Laguna Colorada y géiseres.',
    descriptionEn: '4x4 overland journey between San Pedro de Atacama and Uyuni, crossing the salt flat, Laguna Colorada and geysers.',
    duration: '4 dias / 3 noites',
    availability: 'few-spots',
    adults: 2,
    children: 0,
    featured: true,
    badge: 'popular',
    tags: ['expedição', '4x4', 'aventura', 'salar'],
    includes: ['Veículo 4x4', 'Motorista-guia', 'Hospedagem nos refúgios de sal', 'Todas as refeições', 'Oxigênio a bordo'],
    notIncludes: ['Entradas aos parques bolivianos (aprox. 250 BOB)', 'Bebidas'],
    languages: ['Português', 'Espanhol'],
  },
  {
    id: 'patagonia-glaciares',
    slug: 'patagonia-glaciares',
    name: 'Patagônia dos Glaciares: El Calafate & Perito Moreno — 4 Dias',
    nameEs: 'Patagonia de los Glaciares: El Calafate & Perito Moreno — 4 Días',
    nameEn: 'Patagonia Glaciers: El Calafate & Perito Moreno — 4 Days',
    destination: 'El Calafate',
    country: 'Argentina',
    category: 'packages',
    image: '/images/patagonia-argentina.jpg',
    description: 'Roteiro pela Patagônia Argentina com navegação pelos icebergs e caminhada nas passarelas do grandioso Glaciar Perito Moreno.',
    descriptionEs: 'Ruta por la Patagonia Argentina con navegación entre témpanos y pasarelas del Glaciar Perito Moreno.',
    descriptionEn: 'Patagonia journey with glacier navigation and walking the Perito Moreno boardwalks.',
    duration: '4 dias / 3 noites',
    availability: 'on-request',
    adults: 2,
    children: 0,
    badge: 'new',
    tags: ['patagonia', 'glaciar', 'argentina', 'natureza'],
    includes: ['Transfers aeroporto', 'Hospedagem com café', 'Tour Perito Moreno com navegação Safari Náutico', 'Guia do parque'],
    notIncludes: ['Ingresso ao Parque Nacional Los Glaciares', 'Passagens aéreas'],
    languages: ['Português', 'Espanhol', 'Inglês'],
  },
];

export const destinations = [
  {
    id: 'chile',
    name: 'Chile',
    slug: 'chile',
    image: '/images/valle-de-la-luna.jpg',
    description: 'Do deserto ao fim do mundo.',
    productCount: sampleProducts.filter((p) => p.country === 'Chile').length,
  },
  {
    id: 'peru',
    name: 'Peru',
    slug: 'peru',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    description: 'Civilizações, mistérios e natureza.',
    productCount: sampleProducts.filter((p) => p.country === 'Peru').length,
  },
  {
    id: 'bolivia',
    name: 'Bolívia',
    slug: 'bolivia',
    image: '/images/salar-de-uyuni.jpg',
    description: 'O salar mais incrível da terra.',
    productCount: sampleProducts.filter((p) => p.country === 'Bolívia').length,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    slug: 'argentina',
    image: '/images/patagonia-argentina.jpg',
    description: 'Patagônia, vinhos e tango.',
    productCount: sampleProducts.filter((p) => p.country === 'Argentina').length,
  },
];
